language: python

python:
    - 2.5
    - 2.6
    - 2.7
    - 3.2
    - pypy

# matrix:
#     include:
#         - python: 2.5
#         - python: 2.6
#         - python: 2.7
#         - python: 3.2
#           env: LANG="en_US.utf-8"
#         - python: 3.2
#           env: LANG="C"

install:
    - mkdir testrun
    - if [[ $TRAVIS_PYTHON_VERSION == '2.5' ]]; then pip install --use-mirrors unittest2; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors unittest2; fi
    - pip install . --use-mirrors
    - python setup.py build --build-lib=build/lib

script:
    # Must cd somewhere else so python3 doesn't get confused and run
    # the python2 code from the current directory instead of the installed
    # 2to3 version.
    - nosetests -v -w build/lib hamcrest_unit_test
